version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./myapp/tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./myapp:/workspace
    ports:
      - "1337:3000"
    depends_on:
      - db
